const assert = require('node:assert/strict');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const URL = process.env.LIFE_URL || 'http://127.0.0.1:8765/';
const key='life-daily-v1';
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try {
  const context=await browser.newContext(),page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  const state=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
  await page.goto(URL);
  await page.clock.install();
  await page.locator('#task').fill('Practice one proof');
  await page.locator('#minutes').selectOption('5');
  await page.locator('#focus-form button').click();
  await page.clock.fastForward(60000);
  await page.locator('#pause').click();
  assert.equal((await state()).active.status,'paused');
  const paused=(await state()).active.elapsedMs;
  assert(paused>=60000&&paused<65000);
  await page.reload();
  assert.equal(await page.locator('#pause').textContent(),'Resume');
  await page.clock.fastForward(30000);
  assert.equal((await state()).active.elapsedMs,paused);
  await page.locator('#pause').click();
  await page.locator('#stuck').click();
  await page.locator('[data-reason=confused]').click();
  await page.locator('#tiny-action').fill('Read one line');
  await page.clock.fastForward(15000);
  await page.locator('#return-focus').click();
  assert.equal((await state()).active.returns,1);
  await page.locator('#finish').click();
  await page.locator('#next-step').fill('Try the next proof');
  await page.reload();
  assert.equal(await page.locator('#next-step').inputValue(),'Try the next proof');
  await page.locator('#reflection-form button').click();
  await page.reload();
  assert.equal((await state()).sessions.length,1);
  assert.equal((await state()).sessions[0].note,'Try the next proof');
  assert.equal((await state()).active,null);
  await page.locator('[data-view=night]').click();
  await page.locator('#routine-steps input').first().check();
  await page.locator('#routine-note').fill('Open the math notebook');
  await page.locator('#routine-save').click();
  await page.locator('#back-home').click();
  assert.equal(await page.locator('#task').inputValue(),'Open the math notebook');
  await page.reload();
  assert.equal(await page.locator('#task').inputValue(),'Open the math notebook');
  await page.locator('#focus-form button').click();
  await page.clock.fastForward(301000);
  assert.equal((await state()).active.status,'timeup');
  assert.equal(await page.locator('#extend').isVisible(),true);
  await page.locator('#extend').click();
  assert.equal((await state()).active.targetMs,600000);
  await page.locator('#finish').click();
  await page.locator('#reflection-form button').click();
  await page.locator('#settings-open').click();
  const upload=async data=>{
    await page.locator('#import').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(typeof data==='string'?data:JSON.stringify(data))});
    await page.waitForFunction(()=>document.querySelector('#import').value==='');
  };
  const backup={app:'Signal',data:{sessions:[{id:'signal-1',task:'Imported work',subject:'Math',focusedMs:60000,completedAt:new Date().toISOString()}]}};
  await upload(backup);
  assert.match(await page.locator('#import-status').textContent(),/1 sessions imported/);
  await upload(backup);
  assert.match(await page.locator('#import-status').textContent(),/0 sessions imported/);
  await upload('{bad');
  assert.match(await page.locator('#import-status').textContent(),/not valid JSON/);
  const count=(await state()).sessions.length;
  await page.keyboard.press('Escape');
  await page.reload();
  assert.equal((await state()).sessions.length,count);
  for(const width of [320,390,768,1024,1440]){
    await page.setViewportSize({width,height:900});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow at '+width);
  }
  assert.deepEqual(errors,[]);
  const blocked=await browser.newPage();
  await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('blocked');};});
  await blocked.goto(URL);
  assert.match(await blocked.locator('#notice').textContent(),/Storage is unavailable/);
  console.log('PASS: timer, pause/reload, recovery, reflection, night handoff, timeout/extension, Signal import/dedup, malformed JSON, 5 viewport widths, storage failure, console.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
